import { getCurrentUser, loginCustomer, logoutCustomer, registerCustomer } from './customer.js';
import { addVehicle, getVehicles } from './vehicle.js';
import { getBookings } from './booking.js';

const $ = selector => document.querySelector(selector); const toast = message => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2800); };
const user = getCurrentUser();
if (user) { $('#session-label').textContent = user.name; $('#logout-button').classList.remove('hidden'); $('#welcome-name').textContent = `Hi, ${user.name.split(' ')[0]}`; $('#avatar').textContent = user.name.charAt(0).toUpperCase(); renderSignedIn(); } else renderAuth();
$('#logout-button').addEventListener('click', () => { logoutCustomer(); window.location.reload(); });
$('#add-vehicle-button').addEventListener('click', () => { if (!getCurrentUser()) return toast('Sign in to add a vehicle.'); $('#vehicle-form').classList.toggle('hidden'); });
$('#vehicle-form').addEventListener('submit', event => { event.preventDefault(); const result = addVehicle({ userId: user.id, number: $('#vehicle-number').value, model: $('#vehicle-model').value }); if (!result.success) return toast(Object.values(result.errors)[0]); $('#vehicle-form').reset(); $('#vehicle-form').classList.add('hidden'); renderVehicles(); toast('Vehicle added to your garage.'); });
function renderAuth() { $('#auth-content').innerHTML = `<div class="auth-tabs"><button class="auth-tab active" data-mode="login">Sign in</button><button class="auth-tab" data-mode="register">Create account</button></div><form id="auth-form" class="inline-form"><input id="auth-name" class="hidden" placeholder="Full name"><input id="auth-email" type="email" placeholder="Email address" required><input id="auth-password" type="password" placeholder="Password (6+ characters)" required><button class="button button-dark" type="submit">Continue</button><p id="auth-error" class="form-error"></p></form>`; let mode = 'login'; document.querySelectorAll('.auth-tab').forEach(tab => tab.addEventListener('click', () => { mode = tab.dataset.mode; document.querySelectorAll('.auth-tab').forEach(item => item.classList.toggle('active', item === tab)); $('#auth-name').classList.toggle('hidden', mode !== 'register'); })); $('#auth-form').addEventListener('submit', event => { event.preventDefault(); const details = { name: $('#auth-name').value, email: $('#auth-email').value, password: $('#auth-password').value }; const result = mode === 'login' ? loginCustomer(details) : registerCustomer(details); if (!result.success) return $('#auth-error').textContent = Object.values(result.errors)[0]; window.location.reload(); }); }
function renderSignedIn() { renderVehicles(); renderBookings(); }
function renderVehicles() { const vehicles = getVehicles(user.id); $('#vehicle-list').innerHTML = vehicles.length ? vehicles.map(vehicle => `<div class="vehicle-item"><span class="vehicle-icon">▱</span><div class="vehicle-copy"><strong>${vehicle.number}</strong><small>${vehicle.model}</small></div></div>`).join('') : '<p class="empty-message">Your garage is empty. Add your first vehicle.</p>'; }
function renderBookings() { const bookings = getBookings(user.id); $('#booking-count').textContent = bookings.length; $('#recent-bookings').innerHTML = bookings.length ? bookings.slice(0, 3).map(booking => `<div class="booking-item"><div><strong>${booking.serviceName}</strong><small>${booking.date} · ${booking.time}</small></div><span class="status-pill status-${booking.status}">${booking.status}</span></div>`).join('') : '<p class="empty-message">No appointments yet.</p>'; }
