import { getCurrentUser } from './customer.js';
import { getVehicles } from './vehicle.js';
import { createBooking } from './booking.js';
import { SERVICES, getService } from './validation.js';
const $ = selector => document.querySelector(selector); const user = getCurrentUser();
if (!user) { $('#booking-form').innerHTML = '<div class="empty-state"><h2>Sign in to book a service</h2><p>Return to the overview to create your customer account.</p><a class="button button-primary" href="index.html">Go to overview</a></div>'; } else { renderVehicles(); renderServices(); setMinimumDate(); }
function renderVehicles() { const vehicles = getVehicles(user.id); $('#booking-vehicles').innerHTML = vehicles.length ? vehicles.map((vehicle, index) => `<label class="choice-card ${index === 0 ? 'selected' : ''}"><input type="radio" name="vehicle" value="${vehicle.id}" data-number="${vehicle.number}" ${index === 0 ? 'checked' : ''}><strong>${vehicle.number}</strong><small>${vehicle.model}</small></label>`).join('') : '<p class="empty-message">Add a vehicle on the overview page before booking.</p>'; document.querySelectorAll('input[name="vehicle"]').forEach(input => input.addEventListener('change', updateSelection)); }
function renderServices() { $('#service-options').innerHTML = SERVICES.map((service, index) => `<label class="service-card ${index === 0 ? 'selected' : ''}"><input type="radio" name="service" value="${service.id}" ${index === 0 ? 'checked' : ''}><span class="service-icon">${service.icon}</span><strong>${service.name}</strong><small>${service.duration} · $${service.price}</small></label>`).join(''); document.querySelectorAll('input[name="service"]').forEach(input => input.addEventListener('change', updateSelection)); updateSelection(); }
function setMinimumDate() { const date = new Date(); $('#appointment-date').min = date.toISOString().slice(0, 10); $('#appointment-date').value = date.toISOString().slice(0, 10); $('#appointment-date').addEventListener('change', updateSelection); $('#appointment-time').addEventListener('change', updateSelection); }
function updateSelection() { document.querySelectorAll('.choice-card,.service-card').forEach(card => card.classList.toggle('selected', card.querySelector('input').checked)); const vehicle = document.querySelector('input[name="vehicle"]:checked'); const service = getService(document.querySelector('input[name="service"]:checked')?.value); $('#selection-summary').innerHTML = `<div class="summary-row"><span>Vehicle</span><strong>${vehicle?.dataset.number || 'Not selected'}</strong></div><div class="summary-row"><span>Service</span><strong>${service?.name || 'Not selected'}</strong></div><div class="summary-row"><span>When</span><strong>${$('#appointment-date').value || 'Choose a date'}${$('#appointment-time').value ? ` · ${$('#appointment-time').value}` : ''}</strong></div><div class="summary-row"><span>Estimated total</span><strong>$${service?.price || 0}</strong></div>`; }
$('#booking-form').addEventListener('submit', event => { event.preventDefault(); const vehicle = document.querySelector('input[name="vehicle"]:checked'); const service = document.querySelector('input[name="service"]:checked'); const result = createBooking({ userId: user.id, vehicleId: vehicle?.value, vehicleNumber: vehicle?.dataset.number, serviceId: service?.value, date: $('#appointment-date').value, time: $('#appointment-time').value }); document.querySelectorAll('.field-error').forEach(item => item.textContent = ''); if (!result.success) { if (result.errors.vehicle) $('#vehicle-error').textContent = result.errors.vehicle; if (result.errors.service) $('#service-error').textContent = result.errors.service; if (result.errors.date || result.errors.time) $('#date-error').textContent = result.errors.date || result.errors.time; return; } window.location.href = `index.html?booked=${result.booking.id}`; });
